---
- name: Check if host exists in tower inventory
  gather_facts: false
  hosts: localhost

  tasks:
    - block:
      - name: "Fail if Extra Variable {{ HOSTS }} does not exist in Ansible Tower's inventory"
        fail:
          msg: "{{ item }} does not exist in Ansible Tower's inventory."
        when: "item not in groups['all']" 
        with_items: "{{HOSTS}}"

      rescue:
      - name: Failure to get host in tower inventory
        debug:
          msg: "SYNTBOT_OUTPUT: FAILED: This target host {{ HOSTS }} does not exist in the Ansible Tower Inventory 2L22"
        failed_when: True

- name: Check if host has the right OS
  gather_facts: false
  hosts: "{{ HOSTS }}"
  vars:
    HOSTS:

  tasks:
    - block:
      - name: "Fail if Variable ansible_connection is winrm"
        assert:
          that:
            - ansible_connection != "winrm"
          msg: "playbook is for linux not windows"

      rescue:
      - name: Invalid OS for this playbook
        debug:
          msg: "SYNTBOT_OUTPUT: FAILED: {{ HOSTS }} is a windows cannot run this playbook"
        failed_when: True

- name: Playbook check filesystem / FULL
  gather_facts: false
  hosts: "{{ HOSTS }}"
  become: true
  vars:
    HOSTS:
    THRESHOLD:

  tasks:
    - block:

      - name: Assert that THRESHOLD is provided
        assert:
          that:
            - THRESHOLD | mandatory
            - THRESHOLD is defined
            - THRESHOLD | int != 0
          msg: "Please provide THRESHOLD with a number "

      - name: Check space used filesystem / (%Use)  is less than {{THRESHOLD}}% on {{ HOSTS }}
        shell: df -hP / |awk '{ print $5}' |cut -d% -f1|tail -1
        register: result_use

      - name: Ensure that space used on / {{result_use.stdout}}% is less than {{THRESHOLD}}% on {{ HOSTS }}
        assert:
          that: result_use.stdout |float < {{THRESHOLD}}|float


      - name: Log output for SYNTBOT OK
        debug:
          msg: 
           - "SYNTBOT_OUTPUT: SUCCESSFUL: space used on / is {{result_use.stdout|trim}}%  on {{ HOSTS }}"
           - "SYNTBOT_DISLAY: Percentage space used  / is {{result_use.stdout|trim}}% (it is less than THRESHOLD {{THRESHOLD}}%) on {{HOSTS}}"

      rescue:

      - name: Display file / on {{ HOSTS }}
        shell: "df -h / ;echo \"----- find file size + 500MB ----\"; find / -xdev -type f -size +500M -exec du -sh {} ';' | sort -rh" 
        register: result_display


      - name: Log output for SYNTBOT FAILED
        debug:
          msg: 
           - "SYNTBOT_OUTPUT: SUCCESSFUL: Percentage space used  / is {{result_use.stdout|trim}}% (it is greater than THRESHOLD {{THRESHOLD}}%) on {{HOSTS}}"
           - "SYNTBOT_DISLAY: {{ result_display.stdout }}"
        #failed_when: true 
